FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["XLinkScraper/XLinkScraper.csproj", "XLinkScraper/"]
COPY ["BBCowDataLibrary/BBCowDataLibrary.csproj", "BBCowDataLibrary/"]
RUN dotnet restore "XLinkScraper/XLinkScraper.csproj"
COPY . .
WORKDIR "/src/XLinkScraper"
RUN dotnet build "XLinkScraper.csproj" -c $BUILD_CONFIGURATION -o /app/build
RUN mkdir -p /app/Logs && chmod -R 777 /app/Logs

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "XLinkScraper.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "XLinkScraper.dll"]
