// <auto-generated />
using System;
using BBCowDataLibrary.SQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BBCowDataLibrary.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251223183944_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BB_Cow.Class.ClawTreatment", b =>
                {
                    b.Property<int>("ClawTreatmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Claw_Treatment_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ClawTreatmentId"));

                    b.Property<bool>("BandageLH")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Bandage_LH");

                    b.Property<bool>("BandageLV")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Bandage_LV");

                    b.Property<bool>("BandageRH")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Bandage_RH");

                    b.Property<bool>("BandageRV")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Bandage_RV");

                    b.Property<bool>("BlockLH")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Block_LH");

                    b.Property<bool>("BlockLV")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Block_LV");

                    b.Property<bool>("BlockRH")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Block_RH");

                    b.Property<bool>("BlockRV")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Block_RV");

                    b.Property<string>("ClawFindingLH")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("Claw_Finding_LH");

                    b.Property<string>("ClawFindingLV")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("Claw_Finding_LV");

                    b.Property<string>("ClawFindingRH")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("Claw_Finding_RH");

                    b.Property<string>("ClawFindingRV")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("Claw_Finding_RV");

                    b.Property<string>("EarTagNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Ear_Tag_Number");

                    b.Property<bool>("IsBandageRemoved")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsBandageRemoved");

                    b.Property<DateTime>("TreatmentDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Treatment_Date");

                    b.HasKey("ClawTreatmentId");

                    b.ToTable("Claw_Treatment");
                });

            modelBuilder.Entity("BB_Cow.Class.Cow", b =>
                {
                    b.Property<string>("EarTagNumber")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("Ear_Tag_Number");

                    b.Property<int>("CollarNumber")
                        .HasColumnType("int")
                        .HasColumnName("Collar_Number");

                    b.Property<bool>("IsGone")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("EarTagNumber");

                    b.ToTable("Cow");
                });

            modelBuilder.Entity("BB_Cow.Class.CowTreatment", b =>
                {
                    b.Property<int>("CowTreatmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Cow_Treatment_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CowTreatmentId"));

                    b.Property<DateTime>("AdministrationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Administration_Date");

                    b.Property<string>("EarTagNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Ear_Tag_Number");

                    b.Property<float>("MedicineDosage")
                        .HasColumnType("float")
                        .HasColumnName("Medicine_Dosage");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int")
                        .HasColumnName("Medicine_ID");

                    b.Property<int>("UdderId")
                        .HasColumnType("int")
                        .HasColumnName("COW_QUARTER_ID");

                    b.Property<int>("WhereHowId")
                        .HasColumnType("int")
                        .HasColumnName("WhereHow_ID");

                    b.HasKey("CowTreatmentId");

                    b.ToTable("Cow_Treatment");
                });

            modelBuilder.Entity("BB_Cow.Class.KPI", b =>
                {
                    b.Property<int>("KPIId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KPI_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("KPIId"));

                    b.Property<string>("Script")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("Sort_Order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("KPIId");

                    b.ToTable("KPI");
                });

            modelBuilder.Entity("BB_Cow.Class.Medicine", b =>
                {
                    b.Property<int>("MedicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Medicine_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MedicineId"));

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("Medicine_Name");

                    b.HasKey("MedicineId");

                    b.ToTable("Medicine");
                });

            modelBuilder.Entity("BB_Cow.Class.PlannedClawTreatment", b =>
                {
                    b.Property<int>("PlannedClawTreatmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Planned_Claw_Treatment_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PlannedClawTreatmentId"));

                    b.Property<bool>("ClawFindingLH")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Claw_Finding_LH");

                    b.Property<bool>("ClawFindingLV")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Claw_Finding_LV");

                    b.Property<bool>("ClawFindingRH")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Claw_Finding_RH");

                    b.Property<bool>("ClawFindingRV")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Claw_Finding_RV");

                    b.Property<string>("Desciption")
                        .HasColumnType("longtext")
                        .HasColumnName("Desciption");

                    b.Property<string>("EarTagNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Ear_Tag_Number");

                    b.Property<DateTime>("TreatmentDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Treatment_Date");

                    b.HasKey("PlannedClawTreatmentId");

                    b.ToTable("Planned_Claw_Treatment");
                });

            modelBuilder.Entity("BB_Cow.Class.PlannedCowTreatment", b =>
                {
                    b.Property<int>("PlannedCowTreatmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Planned_Cow_Treatment_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PlannedCowTreatmentId"));

                    b.Property<DateTime>("AdministrationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Administration_Date");

                    b.Property<string>("EarTagNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Ear_Tag_Number");

                    b.Property<bool>("IsFound")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsFound");

                    b.Property<bool>("IsTreatet")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsTreatet");

                    b.Property<float>("MedicineDosage")
                        .HasColumnType("float")
                        .HasColumnName("Medicine_Dosage");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int")
                        .HasColumnName("Medicine_ID");

                    b.Property<int>("UdderId")
                        .HasColumnType("int")
                        .HasColumnName("Udder_ID");

                    b.Property<int>("WhereHowId")
                        .HasColumnType("int")
                        .HasColumnName("WhereHow_ID");

                    b.HasKey("PlannedCowTreatmentId");

                    b.ToTable("Planned_Cow_Treatment");
                });

            modelBuilder.Entity("BB_Cow.Class.Udder", b =>
                {
                    b.Property<int>("UdderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UDDER_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UdderId"));

                    b.Property<bool>("QuarterLH")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Quarter_LH");

                    b.Property<bool>("QuarterLV")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Quarter_LV");

                    b.Property<bool>("QuarterRH")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Quarter_RH");

                    b.Property<bool>("QuarterRV")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Quarter_RV");

                    b.HasKey("UdderId");

                    b.ToTable("Udder");
                });

            modelBuilder.Entity("BB_Cow.Class.WhereHow", b =>
                {
                    b.Property<int>("WhereHowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WhereHow_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WhereHowId"));

                    b.Property<bool>("ShowDialog")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("WhereHowName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("WhereHow_Name");

                    b.HasKey("WhereHowId");

                    b.ToTable("WhereHow");
                });
#pragma warning restore 612, 618
        }
    }
}
