version: '3.8'

networks:
  4cows-network: # Erstelle ein benutzerdefiniertes Netzwerk
    driver: bridge

services:
  4Cows:
    container_name: 4Cows
    image: benjaminbiber/4cows:latest
    depends_on:
      - 4Cows-Db
    ports:
      - "5750:8080"
    environment:
      DB_SERVER: "4Cows-Db"  # Verbindung über den Container-Namen
      DB_User: "root" 
      DB_Password: "4cows"
      DB_DB: "4cows"
    networks:
      - 4cows-network # Nutzt das benutzerdefinierte Netzwerk

  4Cows-DB:
    image: mariadb:latest
    container_name: 4Cows-Db
    environment:
      MYSQL_ROOT_PASSWORD: 4cows
      MYSQL_DATABASE: 4cows
    ports:
      - "3306:3306"
    volumes:
      - /etc/docker_vol/4cows-db:/var/lib/mysql
    networks:
      - 4cows-network # Nutzt das benutzerdefinierte Netzwerk
