name: Test Secrets

on:
  push:
    branches:
      - main

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Test Secrets
        env:
          MY_SECRET: ${{ secrets.DB_DB }}
        run: |
          echo "Secret: $MY_SECRET"
